CREATE TABLE `filings` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ticker` varchar(10) NOT NULL,
  `filing_date` date DEFAULT NULL,
  `filing_type` varchar(10) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expenses_restructuring` DECIMAL(12,1) DEFAULT NULL,
  `expenses_depreciation_amortization` DECIMAL(12,1) DEFAULT NULL,
  `expenses_discontinued_operations` DECIMAL(12,1) DEFAULT NULL,
  `expenses_write_down` DECIMAL(12,1) DEFAULT NULL,
  `expenses_non_recurring_other` DECIMAL(12,1) DEFAULT NULL,
  `expenses_interest` DECIMAL(12,1) DEFAULT NULL,
  `expenses_interest_minority` DECIMAL(12,1) DEFAULT NULL,
  `expenses_legal_regulatory_insurance` DECIMAL(12,1) DEFAULT NULL,
  `expenses_non_operating_company_defined_other` DECIMAL(12,1) DEFAULT NULL,
  `expenses_acquisitions_mergers` DECIMAL(12,1) DEFAULT NULL,
  `expenses_derivative` DECIMAL(12,1) DEFAULT NULL,
  `expenses_foreign_currency` DECIMAL(12,1) DEFAULT NULL,
  `expenses_non_operating_other` DECIMAL(12,1) DEFAULT NULL,
  `expenses_non_operating_other_subsidiary_unconsolidated` DECIMAL(12,1) DEFAULT NULL,
  `expenses_other_financing` DECIMAL(12,1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ticker` (`ticker`),
  KEY `filing_date` (`filing_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;