FROM alpine

RUN apk update \
    && apk add wget \
    && wget https://github.com/skeema/skeema/releases/download/v1.6.0/skeema_1.6.0_linux_amd64.tar.gz \
    && tar xvf skeema_1.6.0_linux_amd64.tar.gz \
    && mv skeema /bin

COPY schemas schemas 
WORKDIR schemas